# Site settings
name: tech • scrolls
description: "A site run by Diego Nieto Cid"
url: "https://www.techscrolls.org"

# Delete the lines you don't need
# about 5 elements are recomended
github_username: diegonc
twitter_username: qualehk
linkedin_username: diegonc
email: dnietoc@gmail.com

avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars0.githubusercontent.com/u/261458?v=3&s=460"

front_img: yes
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"

favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"

# Build settings
markdown: kramdown
permalink: pretty
